services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development} # Use the 'dev' stage by default, or 'build' in production
    volumes:
      - front_dist_volume:/app/dist
      - ./front/app/src:/app/src
    ports:
      - "5173:5173"
    expose:
      - "5173"
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - transcendance_network
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  server:
    container_name: server
    build:
      context: ./server # Build context (directory containing the Dockerfile for server)
      dockerfile: Dockerfile # Dockerfile for this service
    command: >
      sh -c "python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: server.settings
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: ${SECRET_KEY}
      CRON_SECRET: ${CRON_SECRET}
      CRON_ENDPOINT: ${CRON_ENDPOINT}
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - transcendance_network
    stdin_open: true
    tty: true

  crontab:
    container_name: crontab
    build:
      context: ./crontab
      dockerfile: Dockerfile
    environment:
      CRON_SECRET: ${CRON_SECRET}
      CRON_ENDPOINT: ${CRON_ENDPOINT}
      CRON_CSRF_TOKEN: ${CRON_CSRF_TOKEN}
      PYTHONPATH: /app/server
      DJANGO_SETTINGS_MODULE: server.settings
    depends_on:
      - nginx
      - server
      - front
    volumes:
      - ./crontab:/app/crontab
      - ./crontab/scripts:/app/scripts
      - ./server:/app/server
    networks:
      - transcendance_network
    restart: on-failure

  database:
    container_name: database
    build:
      context: ./database # Build context (directory containing the Dockerfile for the database)
      dockerfile: Dockerfile # Dockerfile for this service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports: # Not exposed in production, Django connects via postgres://user:password@db:5432/dbname
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - transcendance_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV} # Pass the NODE_ENV variable to the Nginx build context
    volumes:
      - ./front/app:/app/
      - front_dist_volume:/app/dist:ro
      - media_volume:/app/media/ # Directory containing the application's media files
      - static_volume:/app/static/ # Directory containing the application's static files
      - db_volume:/var/lib/postgresql/data/ # Directory containing the database files
    ports:
      - "1026:1026"
    expose:
      - "1026"
    depends_on:
      - front
      - server
    networks:
      - transcendance_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - "6380:6379"
    volumes:
    - redis_data:/data
    networks:
      - transcendance_network

# shared volumes for all services, and between host and containers. better to mount volumes without bind: docker managed the persistence
volumes:
  redis_data:
    name: redis_data
    
  db_volume:
    name: db_volume

  static_volume:
    name: static_volume

  front_dist_volume:
    name: front_dist_volume

  media_volume:
    name: media_volume

networks:
  transcendance_network:
    driver: bridge

# For static_volume:
# Django collects its static files into this volume using collectstatic
# These files are dynamically generated from various Django apps
# Nginx needs to access these files to serve them
# The shared volume allows both Django and Nginx to access the same files

# For media_volume:
# Media files are uploaded by users
# Django stores these files in this volume
# Nginx must be able to serve them
# The volume is shared because it changes dynamically (new uploads, deletions, etc.)

# In contrast, for front-end files:
# They are static (predefined)
# They do not change dynamically
# They can be mounted directly from the filesystem
# That’s why direct mount is sufficient for the front-end, but shared volumes are needed for the server and media.
