version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - "1025:1025"
    depends_on:
      - back_end

  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendance
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

# Utilisation de inotify-tools pour détecter les changements de fichiers et rebuild l'application
services:
  watch-changed-files:
    build:
      context: .
      dockerfile: ./watch-changed-files/Dockerfile
    volumes:
      - ./watch-changed-files:/app
    command: ["sh", "-c", "inotifywait -m -e modify /app && make rebuild"]
    depends_on:
      - back
      - front
