# Generated by Django 5.1.4 on 2025-04-26 18:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_oauthconnection_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='pending', max_length=7)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GameRoomPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.gameroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(related_name='game_rooms', through='pong.GameRoomPlayer', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winners_score', models.IntegerField()),
                ('losers_score', models.IntegerField()),
                ('elo_change', models.IntegerField()),
                ('winners_elo', models.IntegerField()),
                ('losers_elo', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='users.profile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-date'],
            },
        ),
    ]
