# Generated by Django 5.1.4 on 2025-04-03 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
        ('users', '0004_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='game_rooms', to='users.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='MatchmakingTicket',
        ),
    ]
