# Generated by Django 5.1.4 on 2025-03-23 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('expired', 'Expired')], default='pending', max_length=7)),
            ],
        ),
    ]
