# Generated by Django 5.1.4 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroomplayer',
            name='number_of_connections',
            field=models.IntegerField(default=1),
        ),
    ]
