# Generated by Django 5.1.4 on 2025-03-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_pendingmatch'),
        ('users', '0004_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmatch',
            name='elo_range_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1),
        ),
        migrations.AddField(
            model_name='pendingmatch',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
