# Generated by Django 5.1.4 on 2025-04-11 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_gameroom_delete_matchmakingticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
