# Generated by Django 5.1.4 on 2025-06-03 13:43

import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_gameroomplayer_number_of_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='settings',
            field=models.JSONField(default=pong.models.get_default_game_room_settings, verbose_name='Settings'),
        ),
    ]
