# Generated by Django 5.1.4 on 2025-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_gameroom_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroomplayer',
            name='number_of_connections',
            field=models.IntegerField(default=0),
        ),
    ]
