# Generated by Django 5.1.4 on 2025-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_pendingmatch_elo_range_level_pendingmatch_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingmatch',
            name='elo_range_level',
        ),
        migrations.AlterField(
            model_name='pendingmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=7),
        ),
    ]
