# Generated by Django 5.1.4 on 2025-04-02 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_remove_pendingmatch_elo_range_level_and_more'),
        ('users', '0004_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=7)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='PendingMatch',
        ),
    ]
