# Generated by Django 5.1.4 on 2025-02-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_passwprd_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
