# Generated by Django 5.1.4 on 2025-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
