# Generated by Django 5.1.4 on 2025-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_oauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
