# Generated by Django 5.1.4 on 2025-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useronlinestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='is_online',
        ),
        migrations.AddField(
            model_name='useronlinestatus',
            name='connection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
