# Generated by Django 5.1.4 on 2025-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_forgot_passwprd_token_user_mfa_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forgot_passwprd_token',
        ),
        migrations.AddField(
            model_name='user',
            name='forgot_password_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='forgot_password_token_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_token_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
