# Generated by Django 5.1.4 on 2025-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
