# Generated by Django 5.1.4 on 2025-02-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_forgot_passwprd_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_secret',
        ),
    ]
