# Generated by Django 5.1.4 on 2025-02-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_oauth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_id',
        ),
    ]
