# Generated by Django 5.1.4 on 2025-03-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_match_loser_alter_match_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
