# Generated by Django 5.1.4 on 2025-04-11 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
