# Generated by Django 5.1.4 on 2025-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(default='', max_length=128),
        ),
    ]
