# Generated by Django 5.1.4 on 2025-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_last_activity_alter_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nb_active_connexions',
            field=models.IntegerField(default=0),
        ),
    ]
