# Generated by Django 5.1.4 on 2025-02-12 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_connection_type_remove_user_oauth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(editable=False, max_length=32)),
                ('oauth_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(editable=False, max_length=9)),
                ('connection_type', models.CharField(choices=[('42', '42 School API'), ('github', 'Github API'), ('regular', 'Our Own Auth')], max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
