# Generated by Django 5.1.4 on 2025-02-12 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_oauthconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
