# Generated by Django 5.1.4 on 2025-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_nb_active_connexions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
