# Generated by Django 5.1.6 on 2025-04-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_oauthconnection_date"),
        ("users", "0006_profile_active_channels"),
    ]

    operations = []
