# Generated by Django 5.1.4 on 2025-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_oauthconnection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='state',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
