# Generated by Django 5.1.4 on 2025-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_oauthconnection_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='connection_type',
            field=models.CharField(choices=[('42', '42 School API'), ('github', 'Github API'), ('regular', 'Our Own Auth')], max_length=10),
        ),
    ]
