# Generated by Django 5.1.4 on 2025-04-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250414_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOnlineStatus',
        ),
    ]
