# Generated by Django 5.1.4 on 2025-02-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='issued_at',
        ),
    ]
