# Generated by Django 5.1.4 on 2025-07-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_useronlinestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_channels',
        ),
    ]
