# Generated by Django 5.1.4 on 2025-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_oauthconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='connection_type',
            field=models.CharField(choices=[('42', '42 School API'), ('github', 'Github API'), ('regular', 'Our Own Auth')], max_length=7),
        ),
        migrations.AlterField(
            model_name='oauthconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected')], editable=False, max_length=9),
        ),
    ]
