# Generated by Django 5.1.4 on 2025-01-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_match_losers_elo_match_winners_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='loser_score',
            new_name='losers_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='winner_score',
            new_name='winners_score',
        ),
    ]
