# Generated by Django 5.1.4 on 2025-08-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_active_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('used', 'Used')], editable=False, max_length=9),
        ),
    ]
