# Generated by Django 5.1.4 on 2025-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_oauthconnection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected')], editable=False, max_length=9),
        ),
    ]
