# Generated by Django 5.1.4 on 2025-02-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='no_self_friendship',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
    ]
