# Generated by Django 5.1.4 on 2025-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_friendship_no_self_friendship_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('from_profile', models.F('to_profile')), _negated=True), name='no_self_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='unique_friendship'),
        ),
    ]
