# Generated by Django 5.1.4 on 2025-01-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date'], 'verbose_name_plural': 'matches'},
        ),
    ]
