# Generated by Django 5.1.4 on 2025-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='score',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
