# Generated by Django 5.1.4 on 2025-06-05 18:12

import django.db.models.deletion
import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_gameroom_settings'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='game_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.gameroom'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='settings',
            field=models.JSONField(default=pong.models.get_default_game_room_settings, verbose_name='Settings'),
        ),
    ]
