# Generated by Django 5.1.4 on 2025-06-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='score_p2',
        ),
    ]
