# Generated by Django 5.1.4 on 2025-05-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments_m2m', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participants', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rounds', to='tournaments.tournament'),
        ),
    ]
