# Generated by Django 5.1.4 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
