# Generated by Django 5.1.4 on 2025-08-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_participant_excluded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_at',
        ),
    ]
