# Generated by Django 5.1.4 on 2025-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_bracket_game_room_tournament_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('playing', 'Playing'), ('eliminated', 'Eliminated'), ('winner', 'Winner')], default='registered', max_length=12),
        ),
    ]
