# Generated by Django 5.1.4 on 2025-05-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_participants_alter_participant_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.round'),
        ),
    ]
