# Generated by Django 5.1.4 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_bracket_score_p1_remove_bracket_score_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='game_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
