# Generated by Django 5.1.4 on 2025-08-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='alias',
            field=models.CharField(max_length=255),
        ),
    ]
