# Generated by Django 5.1.4 on 2025-05-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_bracket_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.round'),
        ),
    ]
