# Generated by Django 5.1.4 on 2025-05-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
        ('tournaments', '0004_alter_bracket_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong.match'),
        ),
    ]
