# Generated by Django 5.1.4 on 2025-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='starting', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing'), ('qualified', 'Qualified'), ('eliminated', 'Eliminated'), ('winner', 'Winner')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='starting', max_length=10),
        ),
    ]
