# Generated by Django 5.1.4 on 2025-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_bracket_status_alter_participant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
