# Generated by Django 5.1.4 on 2025-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_bracket_status_alter_round_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='game',
        ),
        migrations.AlterField(
            model_name='bracket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
