# Generated by Django 5.1.4 on 2025-06-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_gameroom_settings'),
        ('tournaments', '0006_alter_bracket_status_alter_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.match'),
        ),
    ]
