# Generated by Django 5.1.4 on 2025-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_bracket_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='score_p2',
        ),
        migrations.AddField(
            model_name='bracket',
            name='losers_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bracket',
            name='winners_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
