# Generated by Django 5.1.4 on 2025-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_bracket_game_alter_bracket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='losers_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bracket',
            name='winners_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
