# Generated by Django 5.1.6 on 2025-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_alter_round_tournament_alter_tournament_participants"),
        ("users", "0008_delete_useronlinestatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="user",
            new_name="profile",
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("profile", "tournament"), ("tournament", "alias")},
        ),
    ]
