# Generated by Django 5.1.4 on 2025-06-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_bracket_losers_score_bracket_winners_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='score_p2',
        ),
    ]
