# Generated by Django 5.1.4 on 2025-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_bracket_game_remove_bracket_score_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='score_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bracket',
            name='score_p2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
