# Generated by Django 5.1.4 on 2025-06-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_bracket_score_p1_remove_bracket_score_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='score_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bracket',
            name='score_p2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
