# Generated by Django 5.1.4 on 2025-06-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_bracket_score_p1_bracket_score_p2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='score_p2',
        ),
    ]
