export async function mockTournamentDetail(id) {
  const data = {
    mockidpending: {
      id: 'mockidpending',
      name: 'Spring Championship',
      status: 'pending',
      tournament_creator: {
        profile: {
          username: 'pedro',
          nickname: 'pedro',
          avatar: '/__mock__/img/sample-pic2.png',
          elo: 2000,
          is_online: true,
        },
        alias: 'Lone Cactus',
      },
      winner: {},
      date: '',
      rounds: [],
      participants: [
        {
          profile: {
            username: 'alex',
            nickname: 'Alex',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1500,
            is_online: false,
          },
          alias: 'Nightmare',
        },
        {
          profile: {
            username: 'pedro',
            nickname: 'pedro',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 1400,
            is_online: true,
          },
          alias: 'Lone Cactus',
        },
        {
          profile: {
            username: 'user3',
            nickname: 'Player Three',
            avatar: '/__mock__/img/sample-pic1.jpg',
            elo: 1450,
            is_online: true,
          },
          alias: 'Midnight Rider',
        },
        {
          profile: {
            username: 'user4',
            nickname: 'Player Four',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 1300,
            is_online: false,
          },
          alias: 'Whiskey Bandit',
        },
        {
          profile: {
            username: 'user5',
            nickname: 'Player Five',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1350,
            is_online: true,
          },
          alias: 'LazyFox',
        },
      ],
      required_participants: 8,
    },
    mockidongoing: {
      id: 'mockidongoing',
      name: 'Spring Championship',
      status: 'ongoing',
      tournament_creator: {
        profile: {
          username: 'pedro',
          avatar: '/__mock__/img/sample-pic2.png',
        },
        alias: 'Lone Cactus',
      },
      winner: {},
      date: '2025-05-09T11:43:42.045Z',
      rounds: [
        {
          number: 1,
          status: 'ongoing',
          brackets: [
            {
              game_id: 'game1',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user2',
                  nickname: 'Player Two',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1400,
                  is_online: true,
                },
                alias: 'Lone Cactus',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              round: 1,
              status: 'finished',
              score_p1: 15,
              score_p2: 5,
            },
            {
              game_id: 'game2',
              participant1: {
                profile: {
                  username: 'user3',
                  nickname: 'Player Three',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1450,
                  is_online: true,
                },
                alias: 'LazyFox',
              },
              participant2: {
                profile: {
                  username: 'user4',
                  nickname: 'Player Four',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1300,
                  is_online: false,
                },
                alias: 'DuskDevil',
              },
              winner: {},
              round: 1,
              status: 'ongoing',
              score_p1: 7,
              score_p2: 5,
            },
            {
              game_id: 'game3',
              participant1: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
                status: 'eliminated',
              },
              participant2: {
                profile: {
                  username: 'user6',
                  nickname: 'Player Six',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1200,
                  is_online: true,
                },
                alias: 'CactusJack',
                status: 'qualified',
              },
              winner: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'CactusJack',
              },
              round: 1,
              status: 'finished',
              score_p1: 2,
              score_p2: 15,
            },
            {
              game_id: 'game4',
              participant1: {
                profile: {
                  username: 'user7',
                  nickname: 'Player Seven',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1250,
                  is_online: true,
                },
                alias: 'Gunslinger',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user8',
                  nickname: 'Player Eight',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1100,
                  is_online: false,
                },
                alias: 'Rustler',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'user7',
                  nickname: 'Player Seven',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1250,
                  is_online: true,
                },
                alias: 'Gunslinger',
              },
              round: 1,
              status: 'finished',
              score_p1: 15,
              score_p2: 0,
            },
          ],
        },
      ],
      participants: [
        {
          profile: {
            username: 'pedro',
            nickname: 'MidnightRider',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1500,
            is_online: false,
          },
          alias: 'MidnightRider',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user2',
            nickname: 'Player Two',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1400,
            is_online: true,
          },
          alias: 'Lone Cactus',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user3',
            nickname: 'Player Three',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 1450,
            is_online: true,
          },
          alias: 'LazyFox',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user4',
            nickname: 'Player Four',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1300,
            is_online: false,
          },
          alias: 'DuskDevil',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user5',
            nickname: 'Player Five',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1350,
            is_online: true,
          },
          alias: 'DirtyHarry',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user6',
            nickname: 'Player Six',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 1200,
            is_online: true,
          },
          alias: 'CactusJack',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user7',
            nickname: 'Player Seven',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1250,
            is_online: true,
          },
          alias: 'Gunslinger',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user8',
            nickname: 'Player Eight',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1100,
            is_online: false,
          },
          alias: 'Rustler',
          status: 'eliminated',
          round: 1,
        },
      ],
      required_participants: 8,
    },
    mockidongoing2: {
      id: 'mockidongoing2',
      name: 'Spring Championship',
      status: 'ongoing',
      tournament_creator: {
        profile: {
          username: 'pedro',
          avatar: '/__mock__/img/sample-pic2.png',
        },
        alias: 'Lone Cactus',
      },
      winner: {},
      date: '2025-05-09T11:43:42.045Z',
      rounds: [
        {
          number: 1,
          status: 'finished',
          brackets: [
            {
              game_id: 'game1',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user2',
                  nickname: 'Player Two',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1400,
                  is_online: true,
                },
                alias: 'Lone Cactus',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              round: 1,
              status: 'finished',
              score_p1: 15,
              score_p2: 5,
            },
            {
              game_id: 'game2',
              participant1: {
                profile: {
                  username: 'user3',
                  nickname: 'Player Three',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1450,
                  is_online: true,
                },
                status: 'eliminated',
                alias: 'LazyFox',
              },
              participant2: {
                profile: {
                  username: 'user4',
                  nickname: 'Player Four',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1300,
                  is_online: false,
                },
                status: 'winner',
                alias: 'DuskDevil',
              },
              winner: {
                profile: {
                  username: 'user4',
                  nickname: 'Player Four',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1300,
                  is_online: false,
                },
                alias: 'DuskDevil',
              },
              round: 1,
              status: 'ongoing',
              score_p1: 7,
              score_p2: 15,
            },
          ],
        },
        {
          number: 2,
          status: 'ongoing',
          brackets: [
            {
              game_id: 'game1',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: '',
              },
              participant2: {
                profile: {
                  username: 'user2',
                  nickname: 'Player Two',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1400,
                  is_online: true,
                },
                alias: 'DuskDevil',
                status: '',
              },
              winner: {},
              round: 2,
              status: 'ongoing',
              score_p1: 5,
              score_p2: 5,
            },
          ],
        },
      ],
      participants: [
        {
          profile: {
            username: 'pedro',
            nickname: 'MidnightRider',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1500,
            is_online: false,
          },
          alias: 'MidnightRider',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user2',
            nickname: 'Player Two',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1400,
            is_online: true,
          },
          alias: 'Lone Cactus',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user3',
            nickname: 'Player Three',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 1450,
            is_online: true,
          },
          alias: 'LazyFox',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user4',
            nickname: 'Player Four',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1300,
            is_online: false,
          },
          alias: 'DuskDevil',
          status: 'eliminated',
          round: 1,
        },
      ],
      required_participants: 4,
    },
    mockidongoing3: {
      tournament_creator: {
        profile: {
          username: 'Rex',
          nickname: 'Good_boy',
          avatar: '/__mock__/img/sample-pic2.png',
          elo: 2307,
          is_online: true,
        },
        alias: 'Good_boy',
        status: 'qualified',
      },
      id: 'dac44d66-7b6e-4ef2-a2e8-89cb0e02e9b2',
      name: 'fgds',
      rounds: [
        {
          number: 1,
          brackets: [
            {
              game_id: '3a9ae84a-c503-41f6-9b8d-a2e95bbc4c9c',
              participant1: {
                profile: {
                  username: 'Grandpa',
                  nickname: 'Old_grumpy',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 2170,
                  is_online: false,
                },
                alias: 'Old_grumpy',
                status: 'eliminated',
              },
              participant2: {
                profile: {
                  username: 'Felix',
                  nickname: 'Deadly_Kitty',
                  avatar: '/img/default_avatar.png',
                  elo: 2126,
                  is_online: true,
                },
                alias: 'Deadly_Kitty',
                status: 'qualified',
              },
              winner: {
                profile: {
                  username: 'Felix',
                  nickname: 'Deadly_Kitty',
                  avatar: '/img/default_avatar.png',
                  elo: 2126,
                  is_online: true,
                },
                alias: 'Deadly_Kitty',
                status: 'qualified',
              },
              status: 'finished',
              score_p1: 0,
              score_p2: 0,
            },
            {
              game_id: 'e0577e4f-443c-4dd8-9fa1-6fe812888d3b',
              participant1: {
                profile: {
                  username: 'Rex',
                  nickname: 'Good_boy',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 2307,
                  is_online: true,
                },
                alias: 'Good_boy',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'Grandma',
                  nickname: 'Old_hag',
                  avatar: '/__mock__/img/sample-pic1.jpg',
                  elo: 2918,
                  is_online: true,
                },
                alias: 'Old_hag',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'Rex',
                  nickname: 'Good_boy',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 2307,
                  is_online: true,
                },
                alias: 'Good_boy',
                status: 'qualified',
              },
              status: 'finished',
              score_p1: 5,
              score_p2: 3,
            },
          ],
          status: 'finished',
        },
        {
          number: 2,
          brackets: [
            {
              game_id: 'a7464478-8bab-4a09-99e2-573186f1bf6c',
              participant1: {
                profile: {
                  username: 'Felix',
                  nickname: 'Deadly_Kitty',
                  avatar: '/img/default_avatar.png',
                  elo: 2126,
                  is_online: true,
                },
                alias: 'Deadly_Kitty',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'Rex',
                  nickname: 'Good_boy',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 2307,
                  is_online: true,
                },
                alias: 'Good_boy',
                status: 'qualified',
              },
              winner: null,
              status: 'ongoing',
              score_p1: 0,
              score_p2: 0,
            },
          ],
          status: 'ongoing',
        },
      ],
      participants: [
        {
          profile: {
            username: 'Grandpa',
            nickname: 'Old_grumpy',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 2170,
            is_online: false,
          },
          alias: 'Old_grumpy',
          status: 'eliminated',
        },
        {
          profile: {
            username: 'Felix',
            nickname: 'Deadly_Kitty',
            avatar: '/img/default_avatar.png',
            elo: 2126,
            is_online: true,
          },
          alias: 'Deadly_Kitty',
          status: 'qualified',
        },
        {
          profile: {
            username: 'Grandma',
            nickname: 'Old_hag',
            avatar: '/__mock__/img/sample-pic1.jpg',
            elo: 2918,
            is_online: true,
          },
          alias: 'Old_hag',
          status: 'eliminated',
        },
        {
          profile: {
            username: 'Rex',
            nickname: 'Good_boy',
            avatar: '/__mock__/img/sample-pic2.png',
            elo: 2307,
            is_online: true,
          },
          alias: 'Good_boy',
          status: 'qualified',
        },
      ],
      status: 'ongoing',
      required_participants: 4,
      date: '2025-07-03T10:11:13.706Z',
      participants_count: 4,
      settings: {
        game_speed: 'medium',
        score_to_win: 5,
        time_limit: 3,
        ranked: false,
        cool_mode: false,
      },
      winner: null,
    },
    mockidfinished: {
      id: 'mockidfinished',
      name: 'Spring Championship',
      status: 'finished',
      tournament_creator: {
        profile: {
          username: 'pedro',
          avatar: '/__mock__/img/sample-pic2.png',
        },
        alias: 'Lone Cactus',
      },
      winner: {
        profile: {
          username: 'pedro',
          nickname: 'MidnightRider',
          avatar: '/__mock__/img/sample-pic2.png',
          elo: 1500,
          is_online: false,
        },
        alias: 'MidnightRider',
        status: 'winner',
        round: 3,
      },
      date: '2025-05-09T11:43:42.045Z',
      rounds: [
        {
          number: 1,
          status: 'finished',
          brackets: [
            {
              game_id: 'game1',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user2',
                  nickname: 'Player Two',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1400,
                  is_online: true,
                },
                alias: 'Lone Cactus',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              round: 1,
              status: 'finished',
              score_p1: 10,
              score_p2: 5,
            },
            {
              game_id: 'game2',
              participant1: {
                profile: {
                  username: 'user3',
                  nickname: 'Player Three',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1450,
                  is_online: true,
                },
                alias: 'LazyFox',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user4',
                  nickname: 'Player Four',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1300,
                  is_online: false,
                },
                alias: 'DuskDevil',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'user3',
                  nickname: 'Player Three',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1450,
                  is_online: true,
                },
                alias: 'LazyFox',
                status: 'qualified',
              },
              round: 1,
              status: 'finished',
              score_p1: 10,
              score_p2: 5,
            },
            {
              game_id: 'game3',
              participant1: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic1.jpg',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user6',
                  nickname: 'Player Six',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1200,
                  is_online: true,
                },
                alias: 'CactusJack',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
              },
              round: 1,
              status: 'finished',
              score_p1: 2,
              score_p2: 1,
            },
            {
              game_id: 'game4',
              participant1: {
                profile: {
                  username: 'user7',
                  nickname: 'Player Seven',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1250,
                  is_online: true,
                },
                alias: 'Gunslinger',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user8',
                  nickname: 'Player Eight',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1100,
                  is_online: false,
                },
                alias: 'Rustler',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'user7',
                  nickname: 'Player Seven',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1250,
                  is_online: true,
                },
                alias: 'Gunslinger',
              },
              round: 1,
              status: 'finished',
              score_p1: 2,
              score_p2: 0,
            },
          ],
        },
        {
          number: 2,
          status: 'finished',
          brackets: [
            {
              game_id: 'game5',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user3',
                  nickname: 'Player Three',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1450,
                  is_online: true,
                },
                alias: 'LazyFox',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              round: 2,
              status: 'finished',
              score_p1: 2,
              score_p2: 1,
            },
            {
              game_id: 'game6',
              participant1: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user7',
                  nickname: 'Player Seven',
                  avatar: '/__mock__/img/sample-pic1.jpg',
                  elo: 1250,
                  is_online: true,
                },
                alias: 'Gunslinger',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
                status: 'qualified',
              },
              round: 2,
              status: 'finished',
              score_p1: 2,
              score_p2: 0,
            },
          ],
        },
        {
          number: 3,
          status: 'finished',
          brackets: [
            {
              game_id: 'final',
              participant1: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              participant2: {
                profile: {
                  username: 'user5',
                  nickname: 'Player Five',
                  avatar: '/__mock__/img/sample-pic3.png',
                  elo: 1350,
                  is_online: true,
                },
                alias: 'DirtyHarry',
                status: 'eliminated',
              },
              winner: {
                profile: {
                  username: 'pedro',
                  nickname: 'MidnightRider',
                  avatar: '/__mock__/img/sample-pic2.png',
                  elo: 1500,
                  is_online: false,
                },
                alias: 'MidnightRider',
                status: 'qualified',
              },
              round: 3,
              status: 'finished',
              score_p1: 2,
              score_p2: 1,
            },
          ],
        },
      ],
      participants: [
        {
          profile: {
            username: 'pedro',
            nickname: 'MidnightRider',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1500,
            is_online: false,
          },
          alias: 'MidnightRider',
          status: 'qualified',
          round: 2,
        },
        {
          profile: {
            username: 'user2',
            nickname: 'Player Two',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1400,
            is_online: true,
          },
          alias: 'Lone Cactus',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user3',
            nickname: 'Player Three',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1450,
            is_online: true,
          },
          alias: 'LazyFox',
          status: 'eliminated',
          round: 2,
        },
        {
          profile: {
            username: 'user4',
            nickname: 'Player Four',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1300,
            is_online: false,
          },
          alias: 'DuskDevil',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user5',
            nickname: 'Player Five',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1350,
            is_online: true,
          },
          alias: 'DirtyHarry',
          status: 'eliminated',
          round: 2,
        },
        {
          profile: {
            username: 'user6',
            nickname: 'Player Six',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1200,
            is_online: true,
          },
          alias: 'CactusJack',
          status: 'eliminated',
          round: 1,
        },
        {
          profile: {
            username: 'user7',
            nickname: 'Player Seven',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1250,
            is_online: true,
          },
          alias: 'Gunslinger',
          status: 'eliminated',
          round: 2,
        },
        {
          profile: {
            username: 'user8',
            nickname: 'Player Eight',
            avatar: '/__mock__/img/sample-pic3.png',
            elo: 1100,
            is_online: false,
          },
          alias: 'Rustler',
          status: 'eliminated',
          round: 1,
        },
      ],
      required_participants: 8,
    },
  };

  return data[id];
}
