# Generated by Django 5.1.4 on 2025-02-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_dialogue_chat_message_delete_privatemessage'),
        ('users', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to='users.profile'),
        ),
    ]
