# Generated by Django 5.1.4 on 2025-05-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_invites', to='chat.gamesession'),
        ),
    ]
