# Generated by Django 5.1.4 on 2025-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_gameinvitation_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
