# Generated by Django 5.1.4 on 2025-03-21 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_notification'),
        ('users', '0003_alter_match_loser_alter_match_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('game_invite', 'game invite'), ('reply_game_invite', 'reply to game invite'), ('new_tournament', 'new tournament'), ('new_friend', 'new friend'), ('message', 'message received')], default='message', max_length=50),
        ),
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], default=None, max_length=11, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='users.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_invites', to='chat.gamesession')),
            ],
        ),
    ]
