# Generated by Django 5.1.4 on 2025-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_gameinvitation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=11),
        ),
    ]
