# Generated by Django 5.1.4 on 2025-03-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_gamesession_notification_type_gameinvitation'),
        ('users', '0003_alter_match_loser_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=11, null=True),
        ),
    ]
