# Generated by Django 5.1.4 on 2025-05-27 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_gameinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
