# Generated by Django 5.1.4 on 2025-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_gameinvitation_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=11),
        ),
    ]
