# Generated by Django 5.1.4 on 2025-05-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_gamesession_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvitation',
            name='game_session',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
