# Generated by Django 5.1.4 on 2025-06-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_gameinvitation_game_session_and_more'),
        ('users', '0008_delete_useronlinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='users.profile'),
        ),
    ]
