# Generated by Django 5.1.4 on 2025-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_tournamentinvitation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentinvitation',
            name='alias',
            field=models.CharField(default='The No Name Tournament', max_length=30),
        ),
    ]
