# Generated by Django 5.1.4 on 2025-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_tournamentinvitation_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='name',
            field=models.CharField(default='The No Name Tournament', max_length=50),
        ),
    ]
