# Generated by Django 5.1.4 on 2025-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_tournamentinvitation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentinvitation',
            name='name',
        ),
        migrations.AddField(
            model_name='tournamentinvitation',
            name='tournament_name',
            field=models.CharField(default='The no name tournament', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='alias',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
