# Generated by Django 5.1.4 on 2025-06-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_tournamentinvitation_name_and_more'),
        ('users', '0008_delete_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='users.profile'),
        ),
    ]
