# Generated by Django 5.1.4 on 2025-08-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_gameinvitation_invitee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinvitation',
            old_name='options',
            new_name='settings',
        ),
    ]
