# Generated by Django 5.1.4 on 2025-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_rename_options_gameinvitation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_really_read',
            field=models.BooleanField(default=False),
        ),
    ]
