# Generated by Django 4.2.18 on 2025-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.png", upload_to="avatars/"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
