# Generated by Django 4.2.7 on 2025-01-18 22:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
