name: Backend Tests

on:
  push:
    branches:
      - main
      - workflows
      - dev
  pull_request:
    branches:
      - workflows
      - main
      - dev

jobs:
  backend:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16.0-bookworm
        env:
          POSTGRES_DB: 'test_db'
          POSTGRES_USER: 'test_user'
          POSTGRES_PASSWORD: 'test_password'
          HOST: 'localhost'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r server/requirements.txt

      - name: Check and fix style errors
        working-directory: server/
        run: |
          ruff check --fix ./users
          ruff format ./users

      - name: Run Django migrations
        working-directory: server/
        env:
          POSTGRES_DB: 'test_db'
          POSTGRES_USER: 'test_user'
          POSTGRES_PASSWORD: 'test_password'
          HOST: 'localhost'
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django unit tests
        working-directory: server/
        env:
          POSTGRES_DB: 'test_db'
          POSTGRES_USER: 'test_user'
          POSTGRES_PASSWORD: 'test_password'
          HOST: 'localhost'

        run: |
          python manage.py test
