name: Backend Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16.0-bookworm
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U $POSTGRES_USER" --health-interval 15s --health-timeout 5s --health-retries 10

    steps:
      - name: Verify PostgreSQL secrets
        run: |
          if [[ -z "${{ secrets.DB_PASSWORD }}" || -z "${{ secrets.DB_USER }}" || -z "${{ secrets.DB_NAME }}" ]]; then
            echo "One or more PostgreSQL secrets are missing!"
            exit 1
          else
            echo "PostgreSQL secrets are set correctly."
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r server/requirements.txt

      - name: Check and fix style errors
        working-directory: server/
        run: |
          ruff check --fix ./users
          ruff format ./users

      - name: Run Django migrations
        working-directory: server/
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django unit tests
        working-directory: server/
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py test
